packages:
  - "apps/site"
  - "apps/extension"
  - "packages/api-types"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp

verifyDepsBeforeRun: false
allowBuilds:
  '@biomejs/biome': true
  esbuild: set this to true or false
  sharp: set this to true or false
